tap "homebrew/bundle"
tap "homebrew/services"

cask "1password"
cask "appcleaner"
cask "docker"
cask "elgato-camera-hub"
cask "expressvpn"
cask "firefox"
cask "google-chrome"
cask "google-drive"
cask "gpg-suite"
cask "macvim"
cask "microsoft-edge"
cask "microsoft-office"
cask "microsoft-teams"
cask "obsidian"
cask "rectangle-pro"
cask "slack"
cask "steam"
cask "the-unarchiver"
cask "transmit"
cask "visual-studio-code"
cask "whatsapp"
cask "zoom"

brew "ack"
brew "direnv"
brew "doctl"
brew "dokku/repo/dokku"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "jq"
brew "mackup"
brew "mas"
brew "node-build"
brew "node"
brew "nodenv"
brew "python"
brew "rbenv"
brew "ruby"
brew "ruby-build"
brew "transcrypt"
brew "tree"
brew "watch"
brew "wget"
brew "zsh"

mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
