#!/bin/sh

set -e

DOTFILES="$HOME/.dotfiles"

echo "Symlinking dotfiles..."
ln -fs "$DOTFILES/ackrc" ~/.ackrc
ln -fs "$DOTFILES/curlrc" ~/.curlrc
ln -fs "$DOTFILES/gemrc" ~/.gemrc
ln -fs "$DOTFILES/gitconfig" ~/.gitconfig
ln -fs "$DOTFILES/gitignore" ~/.gitignore
ln -fs "$DOTFILES/vimrc" ~/.vimrc
ln -fs "$DOTFILES/zshrc" ~/.zshrc

if [ "$(uname -s)" = "Darwin" ]; then
	ln -fs "$DOTFILES/Brewfile" ~/Brewfile
fi