#!/bin/sh

set -e

cd $(dirname $0)/..
DOTFILES=$(pwd -P)

echo "Symlinking dotfiles..."
ln -fs $DOTFILES/ackrc $HOME/.ackrc
ln -fs $DOTFILES/curlrc $HOME/.curlrc
ln -fs $DOTFILES/gemrc $HOME/.gemrc
ln -fs $DOTFILES/gitconfig $HOME/.gitconfig
ln -fs $DOTFILES/gitignore $HOME/.gitignore
ln -fs $DOTFILES/mackup.cfg $HOME/.mackup.cfg
ln -fs $DOTFILES/vimrc $HOME/.vimrc
ln -fs $DOTFILES/zshrc $HOME/.zshrc

if [ "$(uname -s)" = "Darwin" ]; then
	ln -fs $DOTFILES/Brewfile $HOME/.Brewfile
fi
